name: Build and Test the project
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: sudosubin/git-clone-action@v1
      - run: cd chi-compiler-kotlin
      - run: ./gradlew test
