name: Build and Test the project
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: git clone https://github.com/${{github.repository}}
      - name: Build and test
        run: cd chi-compiler-kotlin && ./gradlew test
